name: intray-cli
version: '0.1.0.0'
category: Intray

extra-source-files:
- test_resources/**/*

library:
  source-dirs: src/

  dependencies:
  - autodocodec
  - base >=4.9 && <5
  - bytestring >=0.10
  - containers
  - cookie >=0.4
  - filelock
  - http-client >=0.5
  - http-client-tls >=0.3
  - intray-api
  - intray-cli-data
  - intray-client
  - mergeless
  - mergeless-persistent
  - monad-logger
  - mtl >=2.2
  - network-uri
  - opt-env-conf
  - path >=0.4
  - path-io >=1.2
  - persistent
  - persistent-sqlite
  - pretty-relative-time
  - servant-auth-client >=0.2
  - servant-client >=0.9
  - text >=1.2
  - time
  - typed-process

executables:
  intray:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - intray-cli

tests:
  intray-cli-test:
    main: Spec.hs
    source-dirs: test/
    build-tools: sydtest-discover
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - bytestring
    - genvalidity-path
    - genvalidity-sydtest
    - genvalidity-sydtest-aeson
    - http-client
    - intray-api
    - intray-cli
    - monad-logger
    - mtl
    - opt-env-conf-test
    - path
    - path-io
    - sydtest
    - sydtest-wai
    - text >=1.2
