snapshot: lts-22.39
packages:
- intray-api
- intray-api-gen
- intray-cli
- intray-cli-data
- intray-client

# These are duplicated in nix/overlay.
ghc-options:
  "$locals": -Wall -Wincomplete-uni-patterns -Wincomplete-record-updates -Wpartial-fields -Widentities -Wredundant-constraints -Wcpp-undef -O0 -Wunused-packages

extra-deps:
- github: NorfairKing/opt-env-conf
  commit: 44c868aea2703dddba3d43e23f79bcdb3297eb50
  subdirs:
    - opt-env-conf
    - opt-env-conf-test

- github: NorfairKing/safe-coloured-text
  commit: 046f10147a058c00c2706d98c341219e3cbc7669
  subdirs:
    - safe-coloured-text
    - safe-coloured-text-layout
    - safe-coloured-text-terminfo

- github: NorfairKing/autodocodec
  commit: be4aba9ef133520a8a4087aa26915aaabf1376a7
  subdirs:
    - autodocodec  
    - autodocodec-schema  
    - autodocodec-nix
    - autodocodec-yaml

system-ghc: true
nix:
  enable: false
with-hpack: hpack
