snapshot: lts-23.19
packages:
- intray-api
- intray-api-gen
- intray-cli
- intray-cli-data
- intray-client
- intray-notification

# These are duplicated in nix/overlay.
ghc-options:
  "$locals": -Wall -Wincomplete-uni-patterns -Wincomplete-record-updates -Wpartial-fields -Widentities -Wredundant-constraints -Wcpp-undef -O0 -Wunused-packages
extra-deps:
- opt-env-conf-0.9.0.0@sha256:21d89d24f0f83f6e01ddcbfa688d228e9ddb8489d69a11af1945050605851a2c,1709
- opt-env-conf-test-0.0.0.2@sha256:a4f968e4223977f445e84e515e361e0217a25187fe55aee4f1cd5b911637101d,17412
system-ghc: true
nix:
  enable: false
with-hpack: hpack
