snapshot: lts-22.22
packages:
- intray-api
- intray-api-gen
- intray-cli
- intray-cli-data
- intray-client

# These are duplicated in nix/overlay.
ghc-options:
  "$locals": -Wall -Wincomplete-uni-patterns -Wincomplete-record-updates -Wpartial-fields -Widentities -Wredundant-constraints -Wcpp-undef -O0 -Wunused-packages
  intray-stripe-client: -w # Turn off warnings for the generated code.

system-ghc: true
nix:
  enable: false
with-hpack: hpack
