snapshot: lts-24.38
packages:
- intray-api
- intray-api-gen
- intray-cli
- intray-cli-data
- intray-client
- intray-notification

# These are duplicated in nix/overlay.
ghc-options:
  "$locals": -Wall -Wincomplete-uni-patterns -Wincomplete-record-updates -Wpartial-fields -Widentities -Wredundant-constraints -Wcpp-undef -O0 -Wunused-packages
extra-deps:
- github: NorfairKing/opt-env-conf
  commit: de7ac850e960c28e5182810515a87fbe1d6daede
  subdirs:
    - opt-env-conf
    - opt-env-conf-test
system-ghc: true
nix:
  enable: false
with-hpack: hpack
