name: intray-client
version: '0.0.0.0'
synopsis: Intray Client
default-extensions:
- NoImplicitPrelude

library:
  source-dirs: src
  ghc-options: -Wall

  dependencies:
  - base >=4.7 && <5
  - aeson
  - bytestring >=0.10
  - containers
  - intray-api
  - mergeless
  - servant
  - servant-auth-client
  - servant-client
  - servant-flatten
  - text
  - time
  - typed-uuid
  - validity >=0.4
  - validity-bytestring >=0.2
  - validity-containers >=0.2
  - validity-text >=0.2
  - validity-time >=0.1
  - validity-uuid >=0.0
