name: intray-api
version: '0.0.0.0'
synopsis: Intray API

dependencies:
- base >=4.7 && <5

library:
  source-dirs: src
  ghc-options: -Wall
  dependencies:
  - JuicyPixels
  - JuicyPixels-extra
  - aeson
  - autodocodec
  - base16-bytestring
  - base64-bytestring
  - bcrypt
  - bytestring >=0.10
  - containers
  - http-api-data
  - mergeless
  - monad-logger
  - opt-env-conf
  - path-pieces
  - persistent
  - random
  - servant
  - servant-auth
  - servant-auth-server
  - text
  - time
  - typed-uuid
  - uuid
  - validity >=0.4
  - validity-bytestring >=0.2
  - validity-text >=0.2
  - validity-time >=0.1
  - wai

