name: intray-server
version: '0.0.0.0'
synopsis: Intray Server

dependencies:
- base >=4.7 && <5

library:
  source-dirs: src
  default-extensions:
  - NoImplicitPrelude
  dependencies:
  - aeson
  - aeson-pretty
  - autodocodec
  - autodocodec-yaml
  - bytestring
  - containers
  - envparse
  - http-client
  - intray-api
  - jose
  - mergeless
  - mergeless-persistent
  - monad-logger
  - mtl >=2.2
  - optparse-applicative >=0.13
  - path
  - path-io
  - persistent >=2.7
  - persistent-sqlite
  - pretty-show
  - resourcet
  - servant-auth-server
  - servant-server
  - intray-stripe-client
  - text
  - time
  - typed-uuid
  - wai
  - wai-cors
  - warp >=3.2

executables:
  intray-server:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - intray-server
