name: intray-server-gen
version: '0.0.0.0'
synopsis: Test utils for intray-server

library:
  source-dirs: src
  dependencies:
  - QuickCheck >=2.9
  - base
  - bytestring >=0.10 
  - cookie >=0.4
  - containers
  - genvalidity-bytestring
  - genvalidity-containers
  - genvalidity-sydtest
  - genvalidity-mergeless
  - genvalidity-text
  - genvalidity-time
  - http-client
  - http-types
  - intray-api
  - intray-client
  - intray-data-gen
  - intray-server
  - monad-logger
  - path
  - path-io
  - persistent-sqlite
  - servant-auth-server
  - servant-client
  - servant-server
  - sydtest
  - sydtest-persistent-sqlite
  - sydtest-wai
  - text >=1.2
  - typed-uuid

tests:
  intray-server-test:
    main: Spec.hs
    source-dirs: test
    build-tools: sydtest-discover
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - QuickCheck
    - base >=4.9 && <5
    - bytestring
    - containers
    - genvalidity-bytestring
    - genvalidity-sydtest
    - genvalidity-text
    - genvalidity-time
    - http-types
    - intray-api
    - intray-api-gen
    - intray-client
    - intray-data-gen
    - intray-server
    - intray-server-gen
    - path
    - path-io
    - persistent
    - sydtest
    - sydtest-aeson
    - text

benchmarks:
  intray-server-bench:
    main: Main.hs
    source-dirs: bench
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - bytestring
    - criterion
    - http-client
    - intray-client
    - intray-server-gen
    - sydtest
